# Generated by Django 4.1.5 on 2023-08-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_sendhelp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sendhelp",
            name="author",
        ),
        migrations.RemoveField(
            model_name="sendhelp",
            name="status",
        ),
    ]
