# Generated by Django 3.2.16 on 2022-10-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat1', models.FloatField(verbose_name='ширина1')),
                ('long1', models.FloatField(verbose_name='долгота1')),
                ('lat2', models.FloatField(verbose_name='ширина2')),
                ('long2', models.FloatField(verbose_name='долгота2')),
            ],
        ),
    ]
