# Generated by Django 4.1.5 on 2023-07-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="numberdemo",
            name="number",
            field=models.IntegerField(),
        ),
    ]
