# Generated by Django 4.1.5 on 2023-09-11 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_numberdemo_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="numberdemo",
            name="company",
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="numberdemo",
            name="email",
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
